### ISSUE TITLE
Add favicon to the project

### ISSUE THREAD

**Issue by redcrafter502** [eMTeeWare/emtee-showdown#65]
I made a favicon for this project:
![eMTee Showdown Icon](https://user-images.githubusercontent.com/76687828/112519013-3d6d8600-8d9a-11eb-8053-b7bbdde5ae73.png)

**Comment by methom** [comment]
Thank you, @redcrafter502 . That is a good idea and a nice icon!

**Comment by redcrafter502** [comment]
Here is the Pull Request:
#66
