### ISSUE TITLE
Set meaningful titles for the html pages

### ISSUE THREAD

**Issue by methom** [eMTeeWare/emtee-showdown#74]
Make other titles for the pages in this project:

- eMTee Showdown - Home
- eMTee Showdown - Seasons
- eMTee Showdown - Selection
- eMTee Showdown - Settings
If you have another idea leave a comment!

_Originally posted by @redcrafter502 in https://github.com/eMTeeWare/emtee-showdown/discussions/73_

**Comment by redcrafter502** [comment]
Here is a pull request: #75
